FREIHAND-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/freihand-train/{000000..000001}.tar
INTERHAND26M-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/interhand26m-train/{000000..000001}.tar
HALPE-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/halpe-train/{000000..000001}.tar
COCOW-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/cocow-train/{000000..000001}.tar
MTC-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/mtc-train/{000000..000001}.tar
RHD-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/rhd-train/{000000..000001}.tar
MPIINZSL-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/mpiinzsl-train/{000000..000001}.tar
HO3D-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/ho3d-train/{000000..000001}.tar
H2O3D-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/h2o3d-train/{000000..000001}.tar
DEX-TRAIN:
    TYPE: ImageDataset
    URLS: hamer_training_data/dataset_tars/dex-train/{000000..000001}.tar
# FREIHAND-MOCAP:
    # DATASET_FILE: hamer_training_data/freihand_mocap.npz

